website:
    - 'cd ~/zytekaron.com'
    - 'git pull'
    - 'npm install'
    - 'pm2 restart zytekaron.com'

logbyte:
    - 'cd ~/services/logbyte'
    - 'git pull'
    - 'go get'
    - 'go build main.go -o logbyte'
    - 'sudo mv logbyte /usr/bin'
    - 'sudo systemctl restart logbyte'

cron:
    - 'cd ~/services/cron'
    - 'git pull'
    - 'go get'
    - 'go build main.go -o cron'
    - 'sudo mv cron /usr/bin'
    - 'sudo systemctl restart cron'

notifs:
    - 'cd ~/services/notifs'
    - 'git pull'
    - 'go get'
    - 'go build main.go -o notifs'
    - 'sudo mv notifs /usr/bin'
    - 'sudo systemctl restart notifs'
