website:
  - 'cd /home/z/zytekaron.com'
  - 'git pull'
  - 'npm install'
  - 'sudo website restart'

files:
  - 'cd /home/z/services/fileman'
  - 'git pull'
  - 'go get'
  - 'go build -o fileman main.go'
  - 'sudo fileman restart'

logbyte:
  - 'cd /home/z/services/logbyte'
  - 'git pull'
  - 'go get'
  - 'go build -o logbyte main.go'
  - 'sudo logbyte restart'

cronman:
  - 'cd /home/z/services/cron'
  - 'git pull'
  - 'go get'
  - 'go build -o cronman main.go'
  - 'sudo cronman restart'

notifyr:
  - 'cd /home/z/services/notifs'
  - 'git pull'
  - 'go get'
  - 'go build -o notifyr main.go'
  - 'sudo notifyr restart'

executr:
  - 'cd /home/z/services/executr'
  - 'git pull'
  - 'npm install'
  - 'sudo executr restart'

cronman:
  - 'cd /home/z/services/cronman'
  - 'git pull'
  - 'go get'
  - 'go build -o cronman main.go'
  - 'sudo cronman restart'

