website:
  - 'cd /home/zytekaron/zytekaron.com'
  - 'git pull'
  - 'npm install'
  - 'sudo website restart'

files:
  - 'cd /home/zytekaron/services/fileman'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main fileman'
  - 'sudo fileman restart'

logbyte:
  - 'cd /home/zytekaron/services/logbyte'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main logbyte'
  - 'sudo logbyte restart'

cron:
  - 'cd /home/zytekaron/services/cron'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main cron'
  - 'sudo cron restart'

notifs:
  - 'cd /home/zytekaron/services/notifs'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main notifs'
  - 'sudo notifs restart'

executr:
  - 'cd /home/zytekaron/services/executr'
  - 'git pull'
  - 'npm install'
  - 'sudo executr restart'

cronman:
  - 'cd /home/zytekaron/services/cronman'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main cronman'
  - 'sudo cronman restart'
