website:
  - 'cd ~/zytekaron.com'
  - 'git pull'
  - 'npm install'
  - 'sudo systemctl restart website'

files:
  - 'cd ~/services/fileman'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main fileman'
  - 'sudo systemctl restart fileman'

logbyte:
  - 'cd ~/services/logbyte'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main logbyte'
  - 'sudo systemctl restart logbyte'

cron:
  - 'cd ~/services/cron'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main cron'
  - 'sudo systemctl restart cron'

notifs:
  - 'cd ~/services/notifs'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main notifs'
  - 'sudo systemctl restart notifs'
