website:
  - 'cd ~/zytekaron.com'
  - 'git pull'
  - 'npm install'
  - 'website restart'

files:
  - 'cd ~/services/fileman'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main fileman'
  - 'fileman restart'

logbyte:
  - 'cd ~/services/logbyte'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main logbyte'
  - 'logbyte restart'

cron:
  - 'cd ~/services/cron'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main cron'
  - 'cron restart'

notifs:
  - 'cd ~/services/notifs'
  - 'git pull'
  - 'go get'
  - 'go build main.go'
  - 'mv main notifs'
  - 'notifs restart'
